version: '3'

services:

  neo4j:
    build: ./docker/neo4j/
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_uuid_enabled=true
      - NEO4J_dbms_shell_enabled=true
    volumes:
    - ./docker/neo4j/dbdata:/var/lib/neo4j/data

  gucci-gang:
    build:
      context: ./
      dockerfile: ./docker/gucci-gang/Dockerfile
    command: node build/index.js
    ports:
      - 80:4001
    env_file:
      - .env
    depends_on:
      - neo4j
    volumes:
      - ./public:/gucci-gang/public
      - ./.env:/gucci-gang/build/.env
