# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment Workflow

on:
  push:
    branches: [ master ]

jobs:
  job_one:
    name: Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/gg-wrap/graph-service
            git pull origin master
            git status
            docker-compose up -d --build --remove-orphans
